export const studentStyles = (isDarkMode: boolean) => {
  return {
    container: {
      padding: '12px 4px',
      fontFamily: 'system-ui, sans-serif',
    },
    headerArea: {
      marginBottom: '36px',
    },
    title: {
      fontSize: '32px',
      fontWeight: '800',
      margin: '0 0 8px 0',
      color: isDarkMode ? '#ffffff' : '#2d3748',
      letterSpacing: '-0.02em',
    },
    subtitle: {
      margin: 0,
      color: isDarkMode ? '#94a3b8' : '#718096',
      fontSize: '16px',
      fontWeight: '500',
    },
    grid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
      gap: '28px',
    },
    card: {
      backgroundColor: isDarkMode ? '#111c2a' : '#ffffff',
      borderRadius: '16px',
      overflow: 'hidden',
      boxShadow: isDarkMode 
        ? '0 10px 25px -5px rgba(0, 0, 0, 0.4), 0 8px 10px -6px rgba(0, 0, 0, 0.4)'
        : '0 8px 20px rgba(45, 55, 72, 0.02)',
      border: isDarkMode ? '1px solid #1e293b' : '1px solid #d8e6e2',
      display: 'flex',
      flexDirection: 'column' as const,
      transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    },
    imageContainer: {
      width: '100%',
      height: '190px',
      overflow: 'hidden',
    },
    image: {
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
    },
    contentArea: {
      padding: '24px',
      flexGrow: 1,
      display: 'flex',
      flexDirection: 'column' as const,
    },
    studentName: {
      margin: '0 0 8px 0',
      fontSize: '20px',
      fontWeight: '700',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
      letterSpacing: '-0.01em',
    },
    address: {
      margin: '0 0 16px 0',
      fontSize: '13px',
      color: isDarkMode ? '#818cf8' : '#4a5568',
      fontWeight: '600',
      opacity: isDarkMode ? 1 : 0.8,
    },
    description: {
      margin: '0 0 24px 0',
      fontSize: '14px',
      color: isDarkMode ? '#94a3b8' : '#4a5568',
      lineHeight: '1.6',
      flexGrow: 1,
    },
    actionRow: {
      display: 'flex',
      gap: '12px',
      borderTop: isDarkMode ? '1px solid #1e293b' : '1px solid #edf4f2',
      paddingTop: '20px',
    },
    editButton: {
      padding: '10px 16px',
      borderRadius: '8px',
      backgroundColor: isDarkMode ? 'rgba(148, 163, 184, 0.1)' : '#f0eff5',
      color: isDarkMode ? '#cbd5e0' : '#2d3748',
      border: isDarkMode ? '1px solid #334155' : '1px solid #dcdbe0',
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    viewButton: {
      padding: '10px 22px',
      borderRadius: '8px',
      backgroundColor: isDarkMode ? '#38bdf8' : '#2d3748',
      color: isDarkMode ? '#0f172a' : '#faf8f5',
      border: 'none',
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },

   // FORM & MODAL
   formCard: {
      backgroundColor: isDarkMode ? '#1e293b' : '#ffffff',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
      padding: '32px',
      borderRadius: '12px',
      width: '100%',
      maxWidth: '520px',
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.25)',
      border: `1px solid ${isDarkMode ? '#334155' : '#e2e8f0'}`,
    },
    formGroup: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '6px',
      marginBottom: '16px',
      flex: 1,
    },
    modalOverlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      backdropFilter: 'blur(4px)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
      padding: '20px',
    },
    modalContainer: {
      backgroundColor: isDarkMode ? '#1e293b' : '#faf8f5',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
      width: '100%',
      maxWidth: '520px',
      borderRadius: '12px',
      padding: '28px',
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.25)',
      border: `1px solid ${isDarkMode ? '#334155' : '#e2e8f0'}`,
    },
    rowGroup: {
      display: 'flex',
      gap: '16px',
      marginBottom: '16px',
    },
    inputGroup: {
      display: 'flex',
      flexDirection: 'column',
      flex: 1,
      marginBottom: '16px',
    },
    formLabel: {
      fontSize: '14px',
      fontWeight: '600',
      marginBottom: '6px',
      color: isDarkMode ? '#94a3b8' : '#718096',
    },
    formInput: {
      padding: '10px 12px',
      borderRadius: '8px',
      border: `1px solid ${isDarkMode ? '#334155' : '#dcdbe0'}`,
      backgroundColor: isDarkMode ? '#0f172a' : '#ffffff',
      color: isDarkMode ? '#ffffff' : '#2d3748',
      fontSize: '15px',
      outline: 'none',
      fontFamily: 'inherit',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    }
  };
};