export const appLayoutStyles = (isDarkMode: boolean, isSidebarOpen: boolean) => {
  return {
    appContainer: {
      display: 'flex',
      flexDirection: 'column' as const,
      minHeight: '100vh',
      backgroundColor: isDarkMode ? '#0f172a' : '#faf8f5', 
      color: isDarkMode ? '#f8fafc' : '#2d3748', 
      fontFamily: 'system-ui, -apple-system, sans-serif',
      transition: 'background-color 0.2s ease',
    },
    mainContent: {
      flex: 1,
      padding: '24px',
      width: '100%',
      maxWidth: '1400px',
      margin: '0 auto',
      boxSizing: 'border-box' as const,
    },

    topHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 24px',
      height: '64px',
      backgroundColor: isDarkMode ? '#1e293b' : '#edf4f2',
      borderBottom: isDarkMode ? '1px solid #334155' : '1px solid #d8e6e2',
      boxShadow: isDarkMode ? '0 4px 6px -1px rgba(0, 0, 0, 0.2)' : '0 1px 3px rgba(45, 55, 72, 0.03)',
      position: 'sticky' as const,
      top: 0,
      zIndex: 40,
    },
    headerLogo: {
      fontSize: '18px',
      fontWeight: '700',
      color: isDarkMode ? '#38bdf8' : '#2d3748',
      letterSpacing: '-0.01em',
    },
    navLinksStack: {
      listStyle: 'none',
      padding: 0,
      margin: 0,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '4px',
    },
    navItem: {
      display: 'flex',
      alignItems: 'center',
      padding: '10px 16px',
      borderRadius: '8px',
      textDecoration: 'none',
      fontWeight: '600',
      fontSize: '14px',
      transition: 'all 0.15s ease',
      color: isDarkMode ? '#94a3b8' : '#4a5568',
    },
    
    sidePanel: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      bottom: 0,
      width: '280px',
      backgroundColor: isDarkMode ? '#1e293b' : '#e6eeeb',
      boxShadow: isDarkMode ? '4px 0 24px rgba(0, 0, 0, 0.3)' : '4px 0 24px rgba(45, 55, 72, 0.04)',
      transform: isSidebarOpen ? 'translateX(0)' : 'translateX(-100%)',
      transition: 'transform 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
      zIndex: 50,
      display: 'flex',
      flexDirection: 'column' as const,
      padding: '24px',
      borderRight: isDarkMode ? '1px solid #334155' : '1px solid #d8e6e2',
    },
    hamburgerButton: {
      backgroundColor: isDarkMode ? '#334155' : '#2d3748',
      color: isDarkMode ? '#38bdf8' : '#faf8f5',
      border: 'none',
      borderRadius: '8px',
      width: '40px',
      height: '40px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      transition: 'opacity 0.15s ease',
    },
    backdrop: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: isDarkMode ? 'rgba(0, 0, 0, 0.5)' : 'rgba(45, 55, 72, 0.2)',
      backdropFilter: 'blur(4px)',
      display: isSidebarOpen ? 'block' : 'none',
      zIndex: 45,
    },
    closeButton: {
      alignSelf: 'flex-end',
      background: 'none',
      border: 'none',
      color: isDarkMode ? '#94a3b8' : '#2d3748',
      fontSize: '18px',
      cursor: 'pointer',
      marginBottom: '16px',
      width: '32px',
      height: '32px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoSection: {
      fontSize: '20px',
      fontWeight: '700',
      marginBottom: '28px',
      color: isDarkMode ? '#38bdf8' : '#2d3748',
      letterSpacing: '-0.01em',
    },
    toggleButton: {
      marginTop: 'auto',
      padding: '10px 14px',
      borderRadius: '8px',
      border: 'none',
      backgroundColor: isDarkMode ? '#334155' : '#d8e6e2',
      color: isDarkMode ? '#e2e8f0' : '#2d3748',
      fontWeight: '600',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'opacity 0.15s ease',
    },
  };
};

export const dashboardStyles = (isDarkMode: boolean) => {
  return {
    dashboardLayout: {
      display: 'grid',
      gridTemplateColumns: '1fr 380px',
      gap: '32px',
      alignItems: 'start',
      width: '100%',
      animation: 'fadeIn 0.2s ease-out',
      ['@media (max-width: 1100px)']: {
        gridTemplateColumns: '1fr',
      },
    },
    leftColumn: {
      minWidth: 0,
    },
    rightColumn: {
      backgroundColor: isDarkMode ? '#1e293b' : '#ffffff',
      border: isDarkMode ? '1px solid #334155' : '1px solid #e2e8f0',
      borderRadius: '16px',
      padding: '20px',
      position: 'sticky' as const,
      top: '88px',
      height: 'calc(100vh - 120px)',
      display: 'flex',
      flexDirection: 'column' as const,
      boxShadow: isDarkMode ? '0 4px 20px rgba(0,0,0,0.15)' : '0 4px 12px rgba(45,55,72,0.02)',
    },
    welcomeHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '24px',
      gap: '16px',
    },
    mainTitle: {
      fontSize: '28px',
      fontWeight: '800',
      margin: '0 0 4px 0',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
      letterSpacing: '-0.02em',
    },
    mainSubtitle: {
      margin: 0,
      color: isDarkMode ? '#94a3b8' : '#64748b',
      fontSize: '14px',
    },
    primaryActionButton: {
      backgroundColor: isDarkMode ? '#38bdf8' : '#2d3748',
      color: isDarkMode ? '#0f172a' : '#faf8f5',
      border: 'none',
      padding: '10px 18px',
      borderRadius: '8px',
      fontWeight: '700',
      fontSize: '14px',
      cursor: 'pointer',
      whiteSpace: 'nowrap' as const,
    },
    searchBarRow: {
      marginBottom: '28px',
    },
    globalSearchInput: {
      width: '100%',
      padding: '12px 16px',
      borderRadius: '10px',
      border: isDarkMode ? '1px solid #334155' : '1px solid #cbd5e1',
      backgroundColor: isDarkMode ? '#1e293b' : '#ffffff',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
      fontSize: '14px',
      outline: 'none',
      boxSizing: 'border-box' as const,
    },
    sectionHeaderTitle: {
      fontSize: '16px',
      fontWeight: '700',
      textTransform: 'uppercase' as const,
      letterSpacing: '0.05em',
      color: isDarkMode ? '#94a3b8' : '#64748b',
      margin: '0 0 16px 0',
      borderBottom: isDarkMode ? '1px solid #334155' : '1px solid #e2e8f0',
      paddingBottom: '8px',
    },
    campusTileGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
      gap: '20px',
    },
    hubTileCard: {
      backgroundColor: isDarkMode ? '#1e293b' : '#ffffff',
      border: isDarkMode ? '1px solid #334155' : '1px solid #e2e8f0',
      borderRadius: '12px',
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column' as const,
    },
    tileImageContainer: {
      height: '140px',
      position: 'relative' as const,
      backgroundColor: '#cbd5e1',
    },
    tileImage: {
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
    },
    rosterCountBadge: {
      position: 'absolute' as const,
      bottom: '12px',
      left: '12px',
      backgroundColor: 'rgba(15, 23, 42, 0.75)',
      backdropFilter: 'blur(4px)',
      color: '#ffffff',
      padding: '4px 10px',
      borderRadius: '20px',
      fontSize: '11px',
      fontWeight: '700',
    },
    tileBody: {
      padding: '16px',
      display: 'flex',
      flexDirection: 'column' as const,
      flex: 1,
    },
    tileName: {
      fontSize: '16px',
      fontWeight: '700',
      margin: '0 0 4px 0',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
    },
    tileAddress: {
      fontSize: '12px',
      color: isDarkMode ? '#94a3b8' : '#64748b',
      margin: '0 0 12px 0',
    },
    tileDesc: {
      fontSize: '13px',
      lineHeight: '1.5',
      color: isDarkMode ? '#cbd5e1' : '#4a5568',
      margin: '0 0 16px 0',
      flex: 1,
    },
    tileActions: {
      display: 'flex',
      gap: '10px',
      marginTop: 'auto',
    },
    outlineActionBtn: {
      flex: 1,
      backgroundColor: 'transparent',
      border: isDarkMode ? '1px solid #475569' : '1px solid #cbd5e1',
      color: isDarkMode ? '#cbd5e1' : '#4a5568',
      padding: '8px 12px',
      borderRadius: '6px',
      fontSize: '13px',
      fontWeight: '600',
      cursor: 'pointer',
    },
    solidActionBtn: {
      flex: 1,
      backgroundColor: isDarkMode ? '#334155' : '#f1f5f9',
      border: 'none',
      color: isDarkMode ? '#38bdf8' : '#2d3748',
      padding: '8px 12px',
      borderRadius: '6px',
      fontSize: '13px',
      fontWeight: '700',
      cursor: 'pointer',
    },
    rosterStickyHeader: {
      flexShrink: 0,
      borderBottom: isDarkMode ? '1px solid #334155' : '1px solid #f1f5f9',
      paddingBottom: '14px',
      marginBottom: '10px',
    },
    panelHeaderTitle: {
      margin: 0,
      fontSize: '16px',
      fontWeight: '700',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
    },
    textActionLink: {
      background: 'none',
      border: 'none',
      color: '#38bdf8',
      fontWeight: '700',
      fontSize: '13px',
      cursor: 'pointer',
    },
    filterPillBtn: {
      border: 'none',
      padding: '4px 10px',
      borderRadius: '12px',
      fontSize: '11px',
      fontWeight: '700',
      cursor: 'pointer',
      transition: 'all 0.1s ease',
    },
    rosterScrollArea: {
      flex: 1,
      overflowY: 'auto' as const,
      paddingRight: '4px',
    },
    rosterItemRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      padding: '12px 0',
      borderBottom: isDarkMode ? '1px solid #334155' : '1px solid #f1f5f9',
    },
    rosterAvatar: {
      width: '36px',
      height: '36px',
      borderRadius: '50%',
      objectFit: 'cover' as const,
      backgroundColor: '#cbd5e1',
    },
    rosterName: {
      margin: '0 0 2px 0',
      fontSize: '13px',
      fontWeight: '600',
      color: isDarkMode ? '#f8fafc' : '#2d3748',
      whiteSpace: 'nowrap' as const,
      overflow: 'hidden' as const,
      textOverflow: 'ellipsis' as const,
    },
    rosterSubtext: {
      margin: 0,
      fontSize: '11px',
      color: isDarkMode ? '#94a3b8' : '#64748b',
      whiteSpace: 'nowrap' as const,
      overflow: 'hidden' as const,
      textOverflow: 'ellipsis' as const,
    },
    statusBadge: {
      padding: '2px 6px',
      borderRadius: '8px',
      fontSize: '10px',
      fontWeight: '700',
      display: 'inline-block',
    },
    rosterGpa: {
      margin: '2px 0 0 0',
      fontSize: '11px',
      fontWeight: '600',
      color: isDarkMode ? '#cbd5e1' : '#64748b',
    },
    emptyRosterText: {
      textAlign: 'center' as const,
      color: isDarkMode ? '#64748b' : '#94a3b8',
      fontSize: '13px',
      paddingTop: '32px',
    },
  };
};