export const appLayoutStyles = (isDarkMode: boolean, isSidebarOpen: boolean) => {
  return {
    appContainer: {
      display: 'flex',
      flexDirection: 'column' as const,
      minHeight: '100vh',
      backgroundColor: isDarkMode ? '#0f172a' : '#faf8f5', 
      color: isDarkMode ? '#f8fafc' : '#2d3748', 
      fontFamily: 'system-ui, -apple-system, sans-serif',
      transition: 'background-color 0.2s ease',
    },
    mainContent: {
      flex: 1,
      padding: '24px',
      width: '100%',
      maxWidth: '1400px',
      margin: '0 auto',
      boxSizing: 'border-box' as const,
    },

    topHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 24px',
      height: '64px',
      backgroundColor: isDarkMode ? '#1e293b' : '#edf4f2',
      borderBottom: isDarkMode ? '1px solid #334155' : '1px solid #d8e6e2',
      boxShadow: isDarkMode ? '0 4px 6px -1px rgba(0, 0, 0, 0.2)' : '0 1px 3px rgba(45, 55, 72, 0.03)',
      position: 'sticky' as const,
      top: 0,
      zIndex: 40,
    },
    headerLogo: {
      fontSize: '18px',
      fontWeight: '700',
      color: isDarkMode ? '#38bdf8' : '#2d3748',
      letterSpacing: '-0.01em',
    },
    navLinksStack: {
      listStyle: 'none',
      padding: 0,
      margin: 0,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '4px',
    },
    navItem: {
      display: 'flex',
      alignItems: 'center',
      padding: '10px 16px',
      borderRadius: '8px',
      textDecoration: 'none',
      fontWeight: '600',
      fontSize: '14px',
      transition: 'all 0.15s ease',
      color: isDarkMode ? '#94a3b8' : '#4a5568',
    },
    
    sidePanel: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      bottom: 0,
      width: '280px',
      backgroundColor: isDarkMode ? '#1e293b' : '#e6eeeb',
      boxShadow: isDarkMode ? '4px 0 24px rgba(0, 0, 0, 0.3)' : '4px 0 24px rgba(45, 55, 72, 0.04)',
      transform: isSidebarOpen ? 'translateX(0)' : 'translateX(-100%)',
      transition: 'transform 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
      zIndex: 50,
      display: 'flex',
      flexDirection: 'column' as const,
      padding: '24px',
      borderRight: isDarkMode ? '1px solid #334155' : '1px solid #d8e6e2',
    },
    hamburgerButton: {
      backgroundColor: isDarkMode ? '#334155' : '#2d3748',
      color: isDarkMode ? '#38bdf8' : '#faf8f5',
      border: 'none',
      borderRadius: '8px',
      width: '40px',
      height: '40px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      transition: 'opacity 0.15s ease',
    },
    backdrop: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: isDarkMode ? 'rgba(0, 0, 0, 0.5)' : 'rgba(45, 55, 72, 0.2)',
      backdropFilter: 'blur(4px)',
      display: isSidebarOpen ? 'block' : 'none',
      zIndex: 45,
    },
    closeButton: {
      alignSelf: 'flex-end',
      background: 'none',
      border: 'none',
      color: isDarkMode ? '#94a3b8' : '#2d3748',
      fontSize: '18px',
      cursor: 'pointer',
      marginBottom: '16px',
      width: '32px',
      height: '32px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoSection: {
      fontSize: '20px',
      fontWeight: '700',
      marginBottom: '28px',
      color: isDarkMode ? '#38bdf8' : '#2d3748',
      letterSpacing: '-0.01em',
    },
    toggleButton: {
      marginTop: 'auto',
      padding: '10px 14px',
      borderRadius: '8px',
      border: 'none',
      backgroundColor: isDarkMode ? '#334155' : '#d8e6e2',
      color: isDarkMode ? '#e2e8f0' : '#2d3748',
      fontWeight: '600',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'opacity 0.15s ease',
    },
  };
};